version: '3'
services:
    nginx:
        container_name: movement-nginx
        build:
            context: ./docker
            dockerfile: /nginx/dockerfile
        image: 'iot-nginx'
        restart: unless-stopped
        tty: true
        volumes:
            - './docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf'
        networks:
            - iot
    php-fpm:
        container_name: movement-php
        build:
            context: ./docker
            dockerfile: /php/dockerfile
        volumes:
            - './:/var/www'
        image: 'iot-api:latest'
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        networks:
            - iot
networks:
    iot:
        external: true
